import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../core/auth.service';
import { SupabaseService } from '../../core/supabase.service';

@Component({selector:'app-security-page',imports:[ReactiveFormsModule],template:`
  <section class="page-heading"><div><p class="eyebrow">ACCOUNT SETTINGS</p><h1>Security</h1><p>Update your sign-in details and keep your account protected.</p></div></section>
  <div class="settings-stack">
    <form class="form-card" [formGroup]="emailForm" (ngSubmit)="changeEmail()"><h2>Change email</h2><p>Current email: <strong>{{currentEmail()}}</strong></p><label>New email<input type="email" autocomplete="email" formControlName="newEmail" /></label><label>Current password<input type="password" autocomplete="current-password" formControlName="currentPassword" /></label><button class="button secondary" type="submit" [disabled]="emailSaving()">{{emailSaving()?'Sending…':'Send confirmation'}}</button>@if(emailMessage()){<div class="alert success" role="status">{{emailMessage()}}</div>}@if(emailError()){<div class="alert error" role="alert">{{emailError()}}</div>}</form>
    <form class="form-card" [formGroup]="passwordForm" (ngSubmit)="changePassword()"><h2>Change password</h2><label>Current password<input type="password" autocomplete="current-password" formControlName="currentPassword" /></label><label>New password<input type="password" autocomplete="new-password" formControlName="newPassword" /><small>Use at least 8 characters.</small></label><label>Confirm new password<input type="password" autocomplete="new-password" formControlName="confirmPassword" /></label><button class="button secondary" type="submit" [disabled]="passwordSaving()">{{passwordSaving()?'Updating…':'Update password'}}</button>@if(passwordMessage()){<div class="alert success" role="status">{{passwordMessage()}}</div>}@if(passwordError()){<div class="alert error" role="alert">{{passwordError()}}</div>}</form>
    <section class="form-card danger-zone"><h2>Delete account</h2>@if(auth.role()==='admin'){<p>The protected administrator account cannot be deleted from the app.</p><button class="button danger" type="button" disabled>Delete account</button>}@else{<p>This permanently deletes your profile and account. Active matches you host will be cancelled; completed match records remain without your identity.</p><form [formGroup]="deleteForm" (ngSubmit)="deleteAccount()"><label>Current password<input type="password" autocomplete="current-password" formControlName="currentPassword" /></label><label>Type <strong>DELETE MY ACCOUNT</strong> to confirm<input formControlName="confirmation" autocomplete="off" /></label><button class="button danger" type="submit" [disabled]="deleting()">{{deleting()?'Deleting…':'Permanently delete account'}}</button>@if(deleteError()){<div class="alert error" role="alert">{{deleteError()}}</div>}</form>}</section>
  </div>
`})
export class SecurityPage{
  private readonly fb=inject(FormBuilder);readonly auth=inject(AuthService);private readonly supabase=inject(SupabaseService);private readonly router=inject(Router);
  readonly currentEmail=()=>this.auth.user()?.email??'Unavailable';readonly emailSaving=signal(false);readonly passwordSaving=signal(false);readonly deleting=signal(false);readonly emailMessage=signal('');readonly emailError=signal('');readonly passwordMessage=signal('');readonly passwordError=signal('');readonly deleteError=signal('');
  readonly emailForm=this.fb.nonNullable.group({newEmail:['',[Validators.required,Validators.email]],currentPassword:['',[Validators.required]]});
  readonly passwordForm=this.fb.nonNullable.group({currentPassword:['',[Validators.required]],newPassword:['',[Validators.required,Validators.minLength(8)]],confirmPassword:['',[Validators.required]]});
  readonly deleteForm=this.fb.nonNullable.group({currentPassword:['',[Validators.required]],confirmation:['',[Validators.required,Validators.pattern(/^DELETE MY ACCOUNT$/)]]});
  private async verifyCurrentPassword(password:string){const email=this.currentEmail();const{error}=await this.supabase.client.auth.signInWithPassword({email,password});if(error)throw new Error('The current password is incorrect.');}
  async changeEmail(){this.emailMessage.set('');this.emailError.set('');if(this.emailForm.invalid){this.emailForm.markAllAsTouched();this.emailError.set('Enter a valid email and your current password.');return;}this.emailSaving.set(true);try{const value=this.emailForm.getRawValue();await this.verifyCurrentPassword(value.currentPassword);const{error}=await this.supabase.client.auth.updateUser({email:value.newEmail.trim()});if(error)throw error;this.emailForm.reset();this.emailMessage.set('Confirmation sent. Open the link in your new email to finish the change.');}catch(error){this.emailError.set((error as {message?:string})?.message??'The email could not be changed.');}finally{this.emailSaving.set(false);}}
  async changePassword(){this.passwordMessage.set('');this.passwordError.set('');if(this.passwordForm.invalid){this.passwordForm.markAllAsTouched();this.passwordError.set('Complete all fields. The new password must be at least 8 characters.');return;}const value=this.passwordForm.getRawValue();if(value.newPassword!==value.confirmPassword){this.passwordError.set('The new passwords do not match.');return;}if(value.currentPassword===value.newPassword){this.passwordError.set('Choose a password different from your current password.');return;}this.passwordSaving.set(true);try{await this.verifyCurrentPassword(value.currentPassword);const{error}=await this.supabase.client.auth.updateUser({password:value.newPassword});if(error)throw error;this.passwordForm.reset();this.passwordMessage.set('Password updated successfully.');}catch(error){this.passwordError.set((error as {message?:string})?.message??'The password could not be changed.');}finally{this.passwordSaving.set(false);}}
  async deleteAccount(){this.deleteError.set('');if(this.deleteForm.invalid){this.deleteForm.markAllAsTouched();this.deleteError.set('Enter your current password and the exact confirmation phrase.');return;}this.deleting.set(true);try{const value=this.deleteForm.getRawValue();await this.verifyCurrentPassword(value.currentPassword);const{error}=await this.supabase.client.functions.invoke('delete-account',{body:{confirmation:value.confirmation}});if(error)throw error;await this.supabase.client.auth.signOut({scope:'local'});await this.router.navigate(['/login']);}catch(error){this.deleteError.set((error as {message?:string})?.message??'Your account could not be deleted.');}finally{this.deleting.set(false);}}
}
