import { Component, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
@Component({selector:'app-section-page',imports:[RouterLink],template:`
  <section class="page-heading"><div><p class="eyebrow">{{content.eyebrow}}</p><h1>{{content.title}}</h1><p>{{content.subtitle}}</p></div>@if(content.action){<button class="button primary">{{content.action}}</button>}</section>
  @if(section==='friends'){<div class="people-grid">@for(p of people;track p.name){<article class="person-card"><span class="avatar large">{{p.initials}}</span><h3>{{p.name}}</h3><p>{{p.location}} · {{p.sport}}</p><small>Last active {{p.active}}</small><a class="button secondary full" routerLink="/players/player">View profile</a></article>}</div>}
  @else if(section==='notifications'){<div class="form-card notification-list">@for(n of notifications;track n.text){<a [routerLink]="n.link" [class.unread]="n.unread"><span class="notification-symbol">{{n.symbol}}</span><span><strong>{{n.text}}</strong><small>{{n.time}}</small></span></a>}</div>}
  @else if(section==='feedback'){<form class="form-card feedback-form"><label>Title<input placeholder="What would you like us to know?" /></label><label>Rating<select><option>5 — Excellent</option><option>4 — Good</option><option>3 — Okay</option><option>2 — Needs work</option><option>1 — Poor</option></select></label><label>Description<textarea rows="6" placeholder="Share enough detail to help us improve."></textarea></label><button class="button primary">Send feedback</button></form>}
  @else if(section==='security'){<div class="settings-stack"><section class="form-card"><h2>Change email</h2><label>New email<input type="email" /></label><button class="button secondary">Send confirmation</button></section><section class="form-card"><h2>Change password</h2><label>Current password<input type="password" /></label><label>New password<input type="password" /></label><button class="button secondary">Update password</button></section><section class="form-card danger-zone"><h2>Delete account</h2><p>Permanently delete your account and remove or anonymise your data. This cannot be undone.</p><button class="button danger">Delete my account</button></section></div>}
  @else{<div class="form-card"><div class="timeline-list">@for(i of history;track i.title){<div><span class="date-block"><strong>{{i.day}}</strong><small>{{i.month}}</small></span><span><strong>{{i.title}}</strong><small>{{i.note}}</small></span><span class="status-badge" [class]="i.status">{{i.status}}</span></div>}</div></div>}
`})
export class SectionPage{private readonly route=inject(ActivatedRoute);readonly section=this.route.snapshot.data['section'] as string;readonly map:Record<string,{eyebrow:string;title:string;subtitle:string;action?:string}>={history:{eyebrow:'YOUR GAMES',title:'Match history',subtitle:'Completed, cancelled, hosted, and joined matches.'},friends:{eyebrow:'COMMUNITY',title:'Friends',subtitle:'Players you have connected with.'},'friend-requests':{eyebrow:'COMMUNITY',title:'Friend requests',subtitle:'Manage incoming and outgoing requests.'},notifications:{eyebrow:'UPDATES',title:'Notifications',subtitle:'The latest from your matches and friends.',action:'Mark all as read'},feedback:{eyebrow:'HELP US IMPROVE',title:'Platform feedback',subtitle:'Tell us what is working and what could be better.'},security:{eyebrow:'SETTINGS',title:'Security',subtitle:'Manage your email, password, and account.'}};readonly content=this.map[this.section]??this.map['history'];readonly people=[{initials:'HF',name:'Harith Faiz',location:'Petaling Jaya',sport:'Badminton',active:'today'},{initials:'JL',name:'Joanne Lee',location:'Kuala Lumpur',sport:'Pickleball',active:'2h ago'},{initials:'DL',name:'Daniel Lim',location:'Cheras',sport:'Basketball',active:'yesterday'}];readonly notifications=[{symbol:'✓',text:'Your request to join Badminton Social was accepted.',time:'12 minutes ago',link:'/matches/m1',unread:true},{symbol:'+',text:'Joanne Lee sent you a friend request.',time:'2 hours ago',link:'/friend-requests',unread:true},{symbol:'↻',text:'Sunday Morning Futsal changed its start time.',time:'Yesterday',link:'/matches/m1',unread:false}];readonly history=[{day:'14',month:'SEP',title:'Sunday Morning Futsal',note:'Joined · Arena Sukan, PJ',status:'completed'},{day:'07',month:'SEP',title:'Bangsar Badminton Doubles',note:'Hosted · 8 players',status:'completed'},{day:'31',month:'AUG',title:'KLCC Easy 5K',note:'Joined · KLCC Park',status:'cancelled'}];}
