import { DatePipe, TitleCasePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faCalendarDays, faLocationDot, faMessage, faShieldHalved, faUsers } from '@fortawesome/free-solid-svg-icons';
import { MatchRepository } from '../../core/match.repository';
import { AuthService } from '../../core/auth.service';
import { ImageService } from '../../core/image.service';

interface Participant { id:string;name:string;initials:string;isHost:boolean }
interface RatingDraft { rating:number;comment:string;saved:boolean }

@Component({selector:'app-match-detail-page',imports:[RouterLink,FontAwesomeModule,DatePipe,TitleCasePipe],template:`
  @if(loading()){<div class="empty-state"><h2>Loading match…</h2></div>}
  @else if(error()){<div class="empty-state"><h2>Match could not be loaded</h2><p>{{error()}}</p><button class="button secondary" (click)="load()">Try again</button></div>}
  @else if(match();as item){
    <div class="detail-hero" [style.background-image]="coverImage(item['cover_url'])" [style.background-size]="item['cover_url']?'cover':null" [style.background-position]="item['cover_url']?'center':null"><div class="detail-sport">{{item['sport']}}</div>@if(!item['cover_url']){<div class="court-art detail-court" aria-hidden="true"><div class="court-line vertical"></div><div class="court-line horizontal"></div></div>}</div>
    <section class="detail-layout"><div><div class="detail-title"><div><span class="status-badge" [class]="item['status']">{{item['status']|titlecase}}</span><h1>{{item['title']}}</h1><p>Hosted by <strong>{{item['host_name']}}</strong></p></div>@if(joinState()==='pending'&&!isHost()&&(item['status']==='open'||item['status']==='full')){<button class="button secondary" type="button" [disabled]="cancellingRequest()" (click)="cancelRequest()">{{cancellingRequest()?'Cancelling…':'Cancel request'}}</button>}@else if(joinState()==='accepted'&&!isHost()&&(item['status']==='open'||item['status']==='full')){<button class="button danger" type="button" [disabled]="leaving()" (click)="leaveMatch()">{{leaving()?'Leaving…':'Leave match'}}</button>}@else{<button class="button primary" (click)="requestJoin()" [disabled]="isHost()||requesting()||joinLocked()||item['status']!=='open'">{{isHost()?'You are the host':joinState()==='rejected'?'Request rejected':requesting()?'Sending…':'Request to join'}}</button>}</div>
    @if(message()){<div class="alert success" role="status">{{message()}}</div>}@if(actionError()){<div class="alert error" role="alert">{{actionError()}}</div>}
    <div class="info-grid"><div><fa-icon [icon]="icons.calendar"/><span><strong>{{item['starts_at']|date:'EEEE, d MMMM'}}</strong><small>{{item['starts_at']|date:'h:mm a'}} · {{item['duration_minutes']}} minutes</small></span></div><div><fa-icon [icon]="icons.location"/><span><strong>{{item['location']}}</strong><small>Malaysia</small></span></div><div><fa-icon [icon]="icons.users"/><span><strong>{{item['participant_count']}} of {{item['max_players']}} players</strong><small>{{item['max_players']-item['participant_count']}} places available</small></span></div><div><fa-icon [icon]="icons.shield"/><span><strong>{{item['skill_level']|titlecase}}</strong><small>Required skill level</small></span></div></div>
    <div class="form-card prose-card"><h2>About this match</h2><p>{{item['description']||'The host has not added a description.'}}</p></div>@if(isHost()||joinState()==='accepted'){<div class="form-card"><div class="section-heading"><h2>Players</h2><span>{{participants().length}} people</span></div>@for(player of participants();track player.id){<div class="request-row"><span class="avatar">{{player.initials}}</span><span><strong>{{player.name}}</strong><small>{{player.isHost?'Host':'Participant'}}</small></span>@if(isHost()&&!player.isHost&&item['status']!=='completed'&&item['status']!=='cancelled'){<div><button class="button danger" type="button" [disabled]="removing()===player.id" (click)="removePlayer(player)">{{removing()===player.id?'Removing…':'Remove'}}</button></div>}</div>}</div>@if(item['status']==='completed'){<div class="form-card"><div class="section-heading"><h2>Rate your teammates</h2><span>Completed match</span></div>@for(player of rateablePlayers();track player.id){<div class="review"><div><span class="avatar small">{{player.initials}}</span><span><strong>{{player.name}}</strong><small>{{ratingDraft(player.id).saved?'Your saved rating':'Share your experience'}}</small></span></div><div class="form-grid two"><label>Rating<select class="rating-control" [value]="ratingDraft(player.id).rating" (change)="setRating(player.id,$event)"><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Okay</option><option value="2">2 — Needs work</option><option value="1">1 — Poor</option></select></label><label>Comment<input maxlength="1000" [value]="ratingDraft(player.id).comment" (input)="setComment(player.id,$event)" placeholder="Optional comment" /></label></div><button class="button secondary" type="button" [disabled]="ratingPlayer()===player.id" (click)="savePlayerRating(player)">{{ratingPlayer()===player.id?'Saving…':ratingDraft(player.id).saved?'Update rating':'Save rating'}}</button></div>}@empty{<p>There are no teammates to rate.</p>}</div>}}</div>
    <aside><div class="form-card host-card"><span class="avatar large">{{initials(item['host_name'])}}</span><h3>{{item['host_name']}}</h3><p>Match host</p>@if(isHost()&&(item['status']==='open'||item['status']==='full')){<a class="button secondary full" [routerLink]="['/matches',item['id'],'edit']">Edit match</a>@if(canComplete()){<button class="button primary full" type="button" [disabled]="completing()" (click)="completeMatch()">{{completing()?'Completing…':'Mark completed'}}</button>}<button class="button danger full" type="button" [disabled]="cancelling()" (click)="cancelMatch()">{{cancelling()?'Cancelling…':'Cancel match'}}</button>}</div><div class="form-card"><h3>Match chat</h3>@if(isHost()||joinState()==='accepted'){<p>Coordinate with the accepted team.</p><a class="button secondary full" [routerLink]="['/matches',item['id'],'chat']"><fa-icon [icon]="icons.message"/> Open chat</a>}@else{<p>Chat becomes available after your join request is accepted.</p><button class="button secondary full" disabled><fa-icon [icon]="icons.message"/> Chat locked</button>}</div></aside></section>
  }
`})
export class MatchDetailPage implements OnInit{
  private readonly route=inject(ActivatedRoute);private readonly repository=inject(MatchRepository);private readonly auth=inject(AuthService);private readonly images=inject(ImageService);readonly match=signal<Record<string,any>|null>(null);readonly participants=signal<Participant[]>([]);readonly ratingDrafts=signal<Record<string,RatingDraft>>({});readonly loading=signal(true);readonly error=signal('');readonly actionError=signal('');readonly requesting=signal(false);readonly cancellingRequest=signal(false);readonly cancelling=signal(false);readonly completing=signal(false);readonly leaving=signal(false);readonly removing=signal('');readonly ratingPlayer=signal('');readonly joinState=signal<string|null>(null);readonly message=signal('');readonly icons={calendar:faCalendarDays,location:faLocationDot,users:faUsers,shield:faShieldHalved,message:faMessage};
  ngOnInit(){void this.load();}
  async load(){this.loading.set(true);this.error.set('');try{const id=this.route.snapshot.paramMap.get('id')!;const [match,state]=await Promise.all([this.repository.getById(id),this.repository.getJoinState(id)]);this.match.set(match);this.joinState.set(state);if(match['host_id']===this.auth.user()?.id||state==='accepted'){this.participants.set(await this.repository.getParticipants(id,match['host_id'],match['host_name']));if(match['status']==='completed'){const ratings=await this.repository.getMyRatings(id);const drafts:Record<string,RatingDraft>={};for(const rating of ratings)drafts[rating.rated_user_id]={rating:rating.rating,comment:rating.comment??'',saved:true};this.ratingDrafts.set(drafts);}}else this.participants.set([]);}catch(error){this.error.set(error instanceof Error?error.message:'Please try again.');}finally{this.loading.set(false);}}
  async requestJoin(){const item=this.match();if(!item)return;this.requesting.set(true);this.message.set('');this.actionError.set('');try{await this.repository.requestToJoin(item['id']);this.joinState.set('pending');this.message.set('Your request has been sent to the host.');}catch(error){this.actionError.set(error instanceof Error?error.message:(error as {message?:string})?.message??'The request could not be sent.');}finally{this.requesting.set(false);}}
  async cancelRequest(){const item=this.match();if(!item||!window.confirm(`Cancel your request to join ${item['title']}?`))return;this.cancellingRequest.set(true);this.message.set('');this.actionError.set('');try{await this.repository.cancelJoinRequest(item['id']);this.joinState.set('cancelled');this.message.set('Your join request was cancelled.');}catch(error){this.actionError.set((error as {message?:string})?.message??'The request could not be cancelled.');}finally{this.cancellingRequest.set(false);}}
  async cancelMatch(){const item=this.match();if(!item||!window.confirm(`Cancel ${item['title']}? Players will be notified and this cannot be undone.`))return;this.cancelling.set(true);this.message.set('');this.actionError.set('');try{await this.repository.cancelMatch(item['id']);await this.load();this.message.set('Match cancelled. Players have been notified.');}catch(error){this.actionError.set(error instanceof Error?error.message:(error as {message?:string})?.message??'The match could not be cancelled.');}finally{this.cancelling.set(false);}}
  async completeMatch(){const item=this.match();if(!item||!window.confirm(`Mark ${item['title']} as completed? Players will be able to rate one another.`))return;this.completing.set(true);this.message.set('');this.actionError.set('');try{await this.repository.completeMatch(item['id']);await this.load();this.message.set('Match completed. Player ratings are now open.');}catch(error){this.actionError.set((error as {message?:string})?.message??'The match could not be completed.');}finally{this.completing.set(false);}}
  canComplete(){const item=this.match();if(!item)return false;return Date.now()>=new Date(item['starts_at']).getTime()+Number(item['duration_minutes'])*60_000;}
  async leaveMatch(){const item=this.match();if(!item||!window.confirm(`Leave ${item['title']}? The host will be notified.`))return;this.leaving.set(true);this.message.set('');this.actionError.set('');try{await this.repository.leaveMatch(item['id']);this.joinState.set('cancelled');await this.load();this.message.set('You have left the match.');}catch(error){this.actionError.set(error instanceof Error?error.message:(error as {message?:string})?.message??'You could not leave the match.');}finally{this.leaving.set(false);}}
  async removePlayer(player:Participant){const item=this.match();if(!item||!window.confirm(`Remove ${player.name} from ${item['title']}?`))return;this.removing.set(player.id);this.message.set('');this.actionError.set('');try{await this.repository.removeParticipant(item['id'],player.id);await this.load();this.message.set(`${player.name} was removed from the match.`);}catch(error){this.actionError.set(error instanceof Error?error.message:(error as {message?:string})?.message??'The player could not be removed.');}finally{this.removing.set('');}}
  rateablePlayers(){const userId=this.auth.user()?.id;return this.participants().filter(player=>player.id!==userId);}
  ratingDraft(userId:string){return this.ratingDrafts()[userId]??{rating:5,comment:'',saved:false};}
  setRating(userId:string,event:Event){const rating=Number((event.target as HTMLSelectElement).value);this.ratingDrafts.update(items=>({...items,[userId]:{...this.ratingDraft(userId),rating}}));}
  setComment(userId:string,event:Event){const comment=(event.target as HTMLInputElement).value;this.ratingDrafts.update(items=>({...items,[userId]:{...this.ratingDraft(userId),comment}}));}
  async savePlayerRating(player:Participant){const item=this.match();if(!item)return;const draft=this.ratingDraft(player.id);this.ratingPlayer.set(player.id);this.message.set('');this.actionError.set('');try{await this.repository.saveRating(item['id'],player.id,draft.rating,draft.comment);this.ratingDrafts.update(items=>({...items,[player.id]:{...draft,saved:true}}));this.message.set(`Your rating for ${player.name} was saved.`);}catch(error){this.actionError.set(error instanceof Error?error.message:(error as {message?:string})?.message??'The rating could not be saved.');}finally{this.ratingPlayer.set('');}}
  joinLocked(){return this.joinState()==='pending'||this.joinState()==='accepted'||this.joinState()==='rejected';}
  isHost(){return this.match()?.['host_id']===this.auth.user()?.id;}
  coverImage(path:string|null){const url=this.images.publicUrl('match-covers',path);return url?`linear-gradient(rgba(5,36,70,.28),rgba(5,36,70,.28)), url("${url}")`:null;}
  initials(name:string){return name.split(' ').map(part=>part[0]).slice(0,2).join('');}
}
