import { Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatchRepository } from '../../core/match.repository';
import { ImageService } from '../../core/image.service';

@Component({ selector:'app-match-form-page', imports:[ReactiveFormsModule, RouterLink], template:`
  <section class="page-heading compact"><div><p class="eyebrow">{{editing?'MATCH SETTINGS':'NEW MATCH'}}</p><h1>{{editing?'Edit match':'Create a match'}}</h1><p>Set the essentials so the right players can find you.</p></div></section>
  @if(loading()){<div class="empty-state"><h2>Loading match…</h2></div>}@else{<form class="editor-layout" [formGroup]="form" (ngSubmit)="save()">
    <div class="form-card"><h2>Match details</h2><label>Title<input formControlName="title" placeholder="e.g. Friday night badminton" maxlength="80" /></label><div class="form-grid two"><label>Sport<select formControlName="sport">@for(s of sports;track s){<option>{{s}}</option>}</select></label><label>Required skill<select formControlName="skillLevel"><option value="all_levels">All levels</option><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label></div><div class="form-grid two"><label>Maximum players<input type="number" min="2" max="100" formControlName="maxPlayers" /></label><label>Duration (minutes)<input type="number" min="30" max="480" step="30" formControlName="durationMinutes" /></label></div><label>Location<input formControlName="location" placeholder="Venue or meeting point" /></label><label>Start date and time<input type="datetime-local" formControlName="startsAt" /></label><label>Description<textarea rows="5" formControlName="description" maxlength="1000" placeholder="What should players know?"></textarea></label></div>
    <aside><div class="form-card"><h2>Cover image</h2><label class="upload-box cover-upload" [class.has-preview]="coverPreviewUrl()"><input type="file" accept="image/jpeg,image/png,image/webp" (change)="fileSelected($event)"/>@if(coverPreviewUrl()){<img class="upload-preview cover-preview" [src]="coverPreviewUrl()!" alt="Match cover preview"/>}<span class="upload-copy"><strong>{{coverPreviewUrl()?'Change cover image':editing?'Replace cover image':'Choose an image'}}</strong><span>JPEG, PNG or WebP · max 5 MB</span></span></label>@if(uploadProgress()){<small>Upload {{uploadProgress()}}%</small>}</div><div class="form-card checklist"><h2>Before you publish</h2><p>✓ Date is in the future</p><p>✓ Capacity includes the host</p><p>✓ Location is clear</p></div><div class="form-actions"><a class="button secondary" [routerLink]="editing?['/matches',matchId]:['/matches']">Cancel</a><button class="button primary" type="submit" [disabled]="saving()">{{saving()?'Saving…':editing?'Save changes':'Publish match'}}</button></div>@if(message()){<div class="alert success">{{message()}}</div>}@if(error()){<div class="alert error" role="alert">{{error()}}</div>}</aside>
  </form>}
` })
export class MatchFormPage implements OnInit {
  private readonly fb=inject(FormBuilder); private readonly matches=inject(MatchRepository);private readonly images=inject(ImageService);private readonly router=inject(Router);private readonly route=inject(ActivatedRoute);readonly matchId=this.route.snapshot.paramMap.get('id');readonly editing=!!this.matchId; readonly saving=signal(false);readonly loading=signal(this.editing); readonly message=signal('');readonly error=signal(''); readonly uploadProgress=signal(0);readonly coverPreviewUrl=signal<string|null>(null);
  readonly sports=['Badminton','Basketball','Football','Futsal','Tennis','Volleyball','Running','Swimming','Table Tennis','Pickleball'];
  readonly form=this.fb.nonNullable.group({title:['', [Validators.required,Validators.maxLength(80)]],sport:['Badminton',Validators.required],skillLevel:['all_levels',Validators.required],maxPlayers:[4,[Validators.required,Validators.min(2),Validators.max(100)]],location:['',Validators.required],startsAt:['',Validators.required],durationMinutes:[90,[Validators.required,Validators.min(30),Validators.max(480)]],description:['',Validators.maxLength(1000)],cover:[null as File|null]});
  async ngOnInit(){if(!this.matchId)return;try{const match=await this.matches.getEditableById(this.matchId);const date=new Date(match.starts_at);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());this.form.patchValue({title:match.title,sport:match.sport,skillLevel:match.skill_level,maxPlayers:match.max_players,location:match.location,startsAt:date.toISOString().slice(0,16),durationMinutes:match.duration_minutes,description:match.description??''});this.coverPreviewUrl.set(this.images.publicUrl('match-covers',match.cover_image_path));}catch(error){this.error.set(error instanceof Error?error.message:'The match could not be loaded.');}finally{this.loading.set(false);}}
  fileSelected(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0]??null;this.error.set('');if(!file)return;if(file.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type)){this.error.set('Choose a JPEG, PNG or WebP image no larger than 5 MB.');return;}this.form.controls.cover.setValue(file);const reader=new FileReader();reader.onload=()=>this.coverPreviewUrl.set(typeof reader.result==='string'?reader.result:null);reader.readAsDataURL(file);}
  async save(){this.error.set('');if(this.form.invalid){this.form.markAllAsTouched();this.error.set('Please complete all required fields.');return;}if(new Date(this.form.controls.startsAt.value).getTime()<=Date.now()){this.error.set('Start date and time must be in the future.');return;}this.saving.set(true);this.message.set('');try{if(!this.editing){const id=await this.matches.create(this.form.getRawValue(),value=>this.uploadProgress.set(value));await this.router.navigate(['/matches',id]);}else if(this.matchId){await this.matches.update(this.matchId,this.form.getRawValue(),value=>this.uploadProgress.set(value));await this.router.navigate(['/matches',this.matchId]);}}catch(error){this.error.set(error instanceof Error?error.message:(error as {message?:string})?.message??'The match could not be saved.');}finally{this.saving.set(false);}}
}
