import { TitleCasePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FriendRepository } from '../../core/friend.repository';
import { ImageService } from '../../core/image.service';

@Component({selector:'app-friends-page',imports:[RouterLink,TitleCasePipe],template:`
  <section class="page-heading"><div><p class="eyebrow">COMMUNITY</p><h1>{{view==='requests'?'Friend requests':'Friends'}}</h1><p>{{view==='requests'?'Manage players who want to connect.':'Players in your sports community.'}}</p></div><a class="button secondary" [routerLink]="view==='requests'?'/friends':'/friend-requests'">{{view==='requests'?'View friends':'Friend requests'}}</a></section>
  @if(loading()){<div class="empty-state"><h2>Loading players…</h2></div>}@else if(error()){<div class="alert error">{{error()}}</div>}@else if(view==='requests'){
    @if(incoming().length){<div class="people-grid">@for(request of incoming();track request.id){<article class="person-card"><span class="avatar large">@if(avatarUrl(request.avatarPath);as url){<img [src]="url" [alt]="request.name+' profile photo'"/>}@else{{{initials(request.name)}}}</span><h3>{{request.name}}</h3><p>{{request.location}} · {{request.skill|titlecase}}</p><button class="button primary full" [disabled]="processing()===request.id" (click)="accept(request)">{{processing()===request.id?'Working…':'Accept request'}}</button><button class="button secondary full" [disabled]="processing()===request.id" (click)="decline(request)">Decline</button></article>}</div>}@else{<div class="empty-state"><h2>No incoming requests</h2><p>New friend requests will appear here.</p></div>}
  }@else{
    <section class="section-block"><div class="section-heading"><h2>Your friends</h2></div>@if(friends().length){<div class="people-grid">@for(player of friends();track player.id){<article class="person-card"><span class="avatar large">@if(avatarUrl(player.profile_image_path);as url){<img [src]="url" [alt]="player.first_name+' profile photo'"/>}@else{{{initials(player.first_name+' '+player.last_name)}}}</span><h3>{{player.first_name}} {{player.last_name}}</h3><p>{{player.location||'Malaysia'}} · {{player.skill_level|titlecase}}</p><a class="button secondary full" [routerLink]="['/players',player.id]">View profile</a><button class="button danger full" type="button" [disabled]="processing()===player.id" (click)="removeFriend(player)">{{processing()===player.id?'Removing…':'Remove friend'}}</button></article>}</div>}@else{<p>You have not added any friends yet.</p>}</section>
    <section class="section-block"><div class="section-heading"><h2>Discover players</h2></div><div class="people-grid">@for(player of players();track player.id){<article class="person-card"><span class="avatar large">@if(avatarUrl(player.profile_image_path);as url){<img [src]="url" [alt]="player.first_name+' profile photo'"/>}@else{{{initials(player.first_name+' '+player.last_name)}}}</span><h3>{{player.first_name}} {{player.last_name}}</h3><p>{{player.location||'Malaysia'}} · {{player.skill_level|titlecase}}</p><a class="button secondary full" [routerLink]="['/players',player.id]">View profile</a><button class="button primary full" [disabled]="!!player.requestState||processing()===player.id" (click)="send(player)">{{player.requestState==='friend'?'Friends':player.requestState==='sent'?'Request sent':player.requestState==='received'?'Requested you':processing()===player.id?'Sending…':'Add friend'}}</button></article>}</div></section>
  }
  @if(message()){<div class="alert success">{{message()}}</div>}
`})
export class FriendsPage implements OnInit{
  private readonly repository=inject(FriendRepository);private readonly images=inject(ImageService);readonly view=inject(ActivatedRoute).snapshot.data['view'] as string;readonly loading=signal(true);readonly error=signal('');readonly message=signal('');readonly processing=signal('');readonly players=signal<any[]>([]);readonly friends=signal<any[]>([]);readonly incoming=signal<any[]>([]);
  ngOnInit(){void this.load();}
  async load(){this.loading.set(true);this.error.set('');try{if(this.view==='requests')this.incoming.set(await this.repository.incoming());else{const[players,friends]=await Promise.all([this.repository.players(),this.repository.listFriends()]);this.players.set(players);this.friends.set(friends);}}catch(error){this.error.set((error as {message?:string})?.message??'Players could not be loaded.');}finally{this.loading.set(false);}}
  async send(player:any){this.processing.set(player.id);this.message.set('');try{await this.repository.send(player.id);this.players.update(items=>items.map(item=>item.id===player.id?{...item,requestState:'sent'}:item));this.message.set(`Friend request sent to ${player.first_name} ${player.last_name}.`);}catch(error){this.error.set((error as {message?:string})?.message??'Request could not be sent.');}finally{this.processing.set('');}}
  async accept(request:any){this.processing.set(request.id);try{await this.repository.accept(request.id);this.incoming.update(items=>items.filter(item=>item.id!==request.id));this.message.set(`${request.name} is now your friend.`);}catch(error){this.error.set((error as {message?:string})?.message??'Request could not be accepted.');}finally{this.processing.set('');}}
  async decline(request:any){if(!window.confirm(`Decline ${request.name}'s friend request?`))return;this.processing.set(request.id);this.error.set('');try{await this.repository.reject(request.id);this.incoming.update(items=>items.filter(item=>item.id!==request.id));this.message.set(`${request.name}'s request was declined.`);}catch(error){this.error.set((error as {message?:string})?.message??'Request could not be declined.');}finally{this.processing.set('');}}
  async removeFriend(player:any){const name=`${player.first_name} ${player.last_name}`.trim();if(!window.confirm(`Remove ${name} from your friends?`))return;this.processing.set(player.id);this.error.set('');try{await this.repository.remove(player.id);this.friends.update(items=>items.filter(item=>item.id!==player.id));this.players.update(items=>items.map(item=>item.id===player.id?{...item,requestState:null}:item));this.message.set(`${name} was removed from your friends.`);}catch(error){this.error.set((error as {message?:string})?.message??'Friend could not be removed.');}finally{this.processing.set('');}}
  initials(name:string){return name.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase();}
  avatarUrl(path:string|null|undefined){return this.images.publicUrl('avatars',path);}
}
