import { Component, OnDestroy, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { RealtimeChannel } from '@supabase/supabase-js';
import { SupabaseService } from '../../core/supabase.service';
import { ImageService } from '../../core/image.service';

interface ChatMessage { id:string; senderId:string; initials:string; avatarPath:string|null; sender:string; text:string; time:string; mine:boolean }

@Component({selector:'app-chat-page',imports:[FormsModule],template:`
  <section class="chat-shell"><header><div><span class="avatar">JT</span><span><h1>Match group chat</h1><small><span class="online-dot"></span> {{connectionState()}}</small></span></div></header>
    <div class="messages" aria-live="polite">
      @if(loading()){<div class="empty-state"><h2>Loading messages…</h2></div>}
      @else if(error()){<div class="empty-state"><h2>Chat unavailable</h2><p>{{error()}}</p><button class="button secondary" (click)="load()">Try again</button></div>}
      @else{@for(m of messages();track m.id){<div class="message" [class.mine]="m.mine"><span class="avatar small">@if(avatarUrl(m.avatarPath);as url){<img [src]="url" [alt]="m.sender+' profile photo'"/>}@else{{{m.initials}}}</span><div><span class="sender">{{m.sender}}</span><p>{{m.text}}</p><small>{{m.time}} @if(m.mine){· <button class="text-link" type="button" [disabled]="deleting()===m.id" (click)="deleteMessage(m)">{{deleting()===m.id?'Deleting…':'Delete'}}</button>}</small></div></div>}@empty{<div class="empty-state"><h2>No messages yet</h2><p>Start the conversation with your team.</p></div>}}
    </div>
    @if(hasAccess()){<form class="message-composer" (ngSubmit)="send()"><input [(ngModel)]="draft" name="message" maxlength="1000" placeholder="Message the team" aria-label="Message"/><button class="button primary" [disabled]="sending()||!draft.trim()">{{sending()?'Sending…':'Send'}}</button></form>}
  </section>
`})
export class ChatPage implements OnInit,OnDestroy{
  private readonly supabase=inject(SupabaseService);private readonly images=inject(ImageService);private readonly matchId=inject(ActivatedRoute).snapshot.paramMap.get('id')!;private channel?:RealtimeChannel;draft='';readonly messages=signal<ChatMessage[]>([]);readonly loading=signal(true);readonly sending=signal(false);readonly deleting=signal('');readonly error=signal('');readonly hasAccess=signal(false);readonly connectionState=signal('Connecting…');
  ngOnInit(){void this.load();}
  async load(){this.loading.set(true);this.error.set('');this.hasAccess.set(false);try{const user=this.supabase.user();if(!user)throw new Error('not_authenticated');const [{data:match,error:matchError},{data:request,error:requestError},{data:participant,error:participantError}]=await Promise.all([this.supabase.client.from('matches').select('host_id').eq('id',this.matchId).single(),this.supabase.client.from('match_join_requests').select('status').eq('match_id',this.matchId).eq('user_id',user.id).maybeSingle(),this.supabase.client.from('match_participants').select('match_id').eq('match_id',this.matchId).eq('user_id',user.id).is('removed_at',null).maybeSingle()]);if(matchError)throw matchError;if(requestError)throw requestError;if(participantError)throw participantError;if(match.host_id!==user.id&&request?.status!=='accepted'&&!participant)throw new Error('not_a_member');const {data,error}=await this.supabase.client.from('match_messages').select('id,sender_id,body,created_at').eq('match_id',this.matchId).order('created_at',{ascending:true}).limit(100);if(error)throw error;const senderIds=[...new Set((data??[]).map(item=>item.sender_id))];const {data:profiles,error:profileError}=senderIds.length?await this.supabase.client.from('profiles').select('id,first_name,last_name,profile_image_path').in('id',senderIds):{data:[],error:null};if(profileError)throw profileError;this.messages.set((data??[]).map(item=>this.mapMessage(item,profiles??[])));this.hasAccess.set(true);if(!this.channel)this.subscribe();}catch{this.error.set('Only the host and accepted participants can access this chat.');}finally{this.loading.set(false);}}
  private subscribe(){this.channel=this.supabase.client.channel(`match:${this.matchId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'match_messages',filter:`match_id=eq.${this.matchId}`},payload=>{const row=payload.new as {id:string;sender_id:string;body:string;created_at:string};if(this.messages().some(item=>item.id===row.id))return;void this.addRealtimeMessage(row);}).on('postgres_changes',{event:'DELETE',schema:'public',table:'match_messages',filter:`match_id=eq.${this.matchId}`},payload=>{const id=(payload.old as {id?:string}).id;if(id)this.messages.update(items=>items.filter(item=>item.id!==id));}).subscribe(status=>this.connectionState.set(status==='SUBSCRIBED'?'Connected':status==='CHANNEL_ERROR'?'Connection error':'Connecting…'));}
  async send(){const text=this.draft.trim();if(!text)return;this.sending.set(true);this.error.set('');try{const {data,error}=await this.supabase.client.from('match_messages').insert({match_id:this.matchId,body:text}).select('id,sender_id,body,created_at').single();if(error)throw error;if(!this.messages().some(item=>item.id===data.id))await this.addRealtimeMessage(data);this.draft='';}catch(error){this.error.set((error as {message?:string})?.message??'Message could not be sent.');}finally{this.sending.set(false);}}
  async deleteMessage(message:ChatMessage){if(!message.mine||!window.confirm('Delete this message?'))return;this.deleting.set(message.id);this.error.set('');const{error}=await this.supabase.client.from('match_messages').delete().eq('id',message.id);if(error)this.error.set(error.message);else this.messages.update(items=>items.filter(item=>item.id!==message.id));this.deleting.set('');}
  private mapMessage(item:{id:string;sender_id:string;body:string;created_at:string},profiles:{id:string;first_name:string;last_name:string;profile_image_path:string|null}[]):ChatMessage{const profile=profiles.find(value=>value.id===item.sender_id);const mine=item.sender_id===this.supabase.user()?.id;const name=mine?'You':profile?`${profile.first_name} ${profile.last_name}`:'Player';return{id:item.id,senderId:item.sender_id,initials:mine?'YOU':profile?`${profile.first_name[0]??''}${profile.last_name[0]??''}`:'P',avatarPath:profile?.profile_image_path??null,sender:name,text:item.body,time:this.formatTime(item.created_at),mine};}
  private async addRealtimeMessage(row:{id:string;sender_id:string;body:string;created_at:string}){const{data:profile}=await this.supabase.client.from('profiles').select('id,first_name,last_name,profile_image_path').eq('id',row.sender_id).maybeSingle();this.messages.update(items=>items.some(item=>item.id===row.id)?items:[...items,this.mapMessage(row,profile?[profile]:[])]);}
  avatarUrl(path:string|null){return this.images.publicUrl('avatars',path);}
  private formatTime(value:string){return new Intl.DateTimeFormat('en-MY',{hour:'numeric',minute:'2-digit'}).format(new Date(value));}
  ngOnDestroy(){if(this.channel)void this.supabase.client.removeChannel(this.channel);}
}
