import { DatePipe, TitleCasePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { SupabaseService } from '../../core/supabase.service';

interface AdminFeedback { id:string;user_id:string;title:string;description:string;rating:number;status:string;created_at:string }
interface AdminUser { id:string;name:string;location:string;skill:string;status:'active'|'deactivated';role:'user'|'admin';createdAt:string }
interface AdminMatch { id:string;title:string;sport:string;status:string;startsAt:string;hostName:string;players:number;capacity:number }

@Component({selector:'app-admin-page',imports:[DatePipe,TitleCasePipe,RouterLink],template:`
  <section class="page-heading"><div><p class="eyebrow">ADMINISTRATION</p><h1>{{title}}</h1><p>Protected platform management and activity overview.</p></div></section>
  @if(loading()){<div class="empty-state"><h2>Loading administration data…</h2></div>}
  @else if(error()){<div class="alert error">{{error()}}</div>}
  @else if(view==='overview'){
    <div class="metric-grid admin"><div><span>Total users</span><strong>{{metrics().users}}</strong><small>Registered accounts</small></div><div><span>Total matches</span><strong>{{metrics().matches}}</strong><small>All match statuses</small></div><div><span>Pending requests</span><strong>{{metrics().requests}}</strong><small>Awaiting hosts</small></div><div><span>Unread feedback</span><strong>{{metrics().feedback}}</strong><small>Needs review</small></div></div>
    <div class="people-grid"><a class="person-card" routerLink="/admin/users"><h3>User management</h3><p>Review roles and account status.</p></a><a class="person-card" routerLink="/admin/matches"><h3>Match management</h3><p>Inspect matches across the platform.</p></a><a class="person-card" routerLink="/admin/feedback"><h3>Feedback management</h3><p>Read and manage user submissions.</p></a></div>
  }@else if(view==='users'){
    <div class="form-card"><div class="section-heading"><h2>Registered users</h2><span>{{users().length}} accounts</span></div><div class="data-table"><div class="table-row header"><span>User</span><span>Location / skill</span><span>Role</span><span>Status</span></div>@for(user of users();track user.id){<div class="table-row"><span><strong>{{user.name}}</strong><small>Joined {{user.createdAt|date:'d MMM y'}}</small></span><span>{{user.location}} · {{user.skill|titlecase}}</span><span>{{user.role|titlecase}}</span><span>@if(user.role==='admin'){<span class="status-badge open">Protected admin</span>}@else{<button class="button secondary" type="button" [disabled]="processing()===user.id" (click)="toggleUser(user)">{{processing()===user.id?'Saving…':user.status==='active'?'Deactivate':'Reactivate'}}</button>}</span></div>}</div></div>
  }@else if(view==='matches'){
    <div class="form-card"><div class="section-heading"><h2>Platform matches</h2><span>{{matches().length}} matches</span></div><div class="data-table"><div class="table-row header"><span>Match</span><span>Host / date</span><span>Players</span><span>Status</span></div>@for(match of matches();track match.id){<div class="table-row"><span><a [routerLink]="['/matches',match.id]"><strong>{{match.title}}</strong></a><small>{{match.sport}}</small></span><span>{{match.hostName}} · {{match.startsAt|date:'d MMM y'}}</span><span>{{match.players}}/{{match.capacity}}</span><span class="status-badge" [class]="match.status">{{match.status|titlecase}}</span></div>}</div></div>
  }@else if(view==='feedback'){
    @if(feedback().length){<div class="form-card"><div class="section-heading"><h2>Platform feedback</h2><span>{{feedback().length}} submissions</span></div>@for(item of feedback();track item.id){<article class="review"><div><span><strong>{{item.title}}</strong><small>{{item.rating}}/5 · {{item.status}} · {{item.created_at|date:'d MMM, h:mm a'}}</small></span></div><p>{{item.description}}</p><div class="form-actions"><button class="button secondary" type="button" (click)="toggleRead(item)">Mark {{item.status==='read'?'unread':'read'}}</button><button class="button danger" type="button" (click)="remove(item)">Delete</button></div></article>}</div>}@else{<div class="empty-state"><h2>No feedback</h2></div>}
  }@else{<div class="empty-state"><h2>This administration view is not available yet.</h2></div>}
`})
export class AdminPage implements OnInit{
  private readonly supabase=inject(SupabaseService);readonly view=inject(ActivatedRoute).snapshot.data['view'] as string;readonly title=({overview:'Admin overview',users:'User management','user-detail':'User details',matches:'Match management','match-detail':'Match details',feedback:'Feedback management'} as Record<string,string>)[this.view]??'Admin overview';
  readonly feedback=signal<AdminFeedback[]>([]);readonly users=signal<AdminUser[]>([]);readonly matches=signal<AdminMatch[]>([]);readonly metrics=signal({users:0,matches:0,requests:0,feedback:0});readonly loading=signal(true);readonly error=signal('');readonly processing=signal('');
  ngOnInit(){void this.load();}
  async load(){this.loading.set(true);this.error.set('');try{if(this.view==='overview')await this.loadOverview();else if(this.view==='users')await this.loadUsers();else if(this.view==='matches')await this.loadMatches();else if(this.view==='feedback')await this.loadFeedback();}catch(error){this.error.set(error instanceof Error?error.message:(error as {message?:string})?.message??'Administration data could not be loaded.');}finally{this.loading.set(false);}}
  async loadOverview(){const [users,matches,requests,feedback]=await Promise.all([this.supabase.client.from('profiles').select('id',{count:'exact',head:true}),this.supabase.client.from('matches').select('id',{count:'exact',head:true}),this.supabase.client.from('match_join_requests').select('id',{count:'exact',head:true}).eq('status','pending'),this.supabase.client.from('feedback').select('id',{count:'exact',head:true}).eq('status','unread')]);const error=users.error??matches.error??requests.error??feedback.error;if(error)throw error;this.metrics.set({users:users.count??0,matches:matches.count??0,requests:requests.count??0,feedback:feedback.count??0});}
  async loadUsers(){const [{data:profiles,error},{data:roles,error:roleError}]=await Promise.all([this.supabase.client.from('profiles').select('id,first_name,last_name,location,skill_level,status,created_at').order('created_at'),this.supabase.client.from('user_roles').select('user_id,role')]);if(error||roleError)throw error??roleError;const roleMap=new Map((roles??[]).map(item=>[item.user_id,item.role]));this.users.set((profiles??[]).map(profile=>({id:profile.id,name:`${profile.first_name} ${profile.last_name}`.trim(),location:profile.location??'Not specified',skill:profile.skill_level,status:profile.status,role:roleMap.get(profile.id)??'user',createdAt:profile.created_at})));}
  async loadMatches(){const {data,error}=await this.supabase.client.from('matches').select('id,title,sport,status,starts_at,host_id,participant_count,max_players').order('starts_at',{ascending:false});if(error)throw error;const hostIds=[...new Set((data??[]).map(match=>match.host_id).filter((id):id is string=>id!==null))];const {data:hosts,error:hostError}=hostIds.length?await this.supabase.client.from('profiles').select('id,first_name,last_name').in('id',hostIds):{data:[],error:null};if(hostError)throw hostError;const names=new Map((hosts??[]).map(host=>[host.id,`${host.first_name} ${host.last_name}`.trim()]));this.matches.set((data??[]).map(match=>({id:match.id,title:match.title,sport:match.sport,status:match.status,startsAt:match.starts_at,hostName:match.host_id?names.get(match.host_id)??'Unknown host':'Deleted user',players:match.participant_count,capacity:match.max_players})));}
  async loadFeedback(){const{data,error}=await this.supabase.client.from('feedback').select('id,user_id,title,description,rating,status,created_at').order('created_at',{ascending:false});if(error)throw error;this.feedback.set(data??[]);}
  async toggleUser(user:AdminUser){if(user.role==='admin')return;const status=user.status==='active'?'deactivated':'active';if(!window.confirm(`${status==='deactivated'?'Deactivate':'Reactivate'} ${user.name}'s account?`))return;this.processing.set(user.id);const{error}=await this.supabase.client.from('profiles').update({status}).eq('id',user.id);if(error)this.error.set(error.message);else this.users.update(items=>items.map(item=>item.id===user.id?{...item,status}:item));this.processing.set('');}
  async toggleRead(item:AdminFeedback){const status=item.status==='read'?'unread':'read';const{error}=await this.supabase.client.from('feedback').update({status}).eq('id',item.id);if(!error)this.feedback.update(items=>items.map(value=>value.id===item.id?{...value,status}:value));}
  async remove(item:AdminFeedback){if(!window.confirm(`Delete feedback "${item.title}"?`))return;const{error}=await this.supabase.client.from('feedback').delete().eq('id',item.id);if(!error)this.feedback.update(items=>items.filter(value=>value.id!==item.id));}
}
