import { DatePipe, DecimalPipe } from '@angular/common';
import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/auth.service';
import { Database } from '../../core/database.types';
import { SupabaseService } from '../../core/supabase.service';
import { FriendRepository } from '../../core/friend.repository';
import { ImageService } from '../../core/image.service';

type Profile = Database['public']['Tables']['profiles']['Row'];
interface Review { id:string; rating:number; comment:string; name:string; initials:string; createdAt:string }

@Component({selector:'app-profile-page',imports:[RouterLink,ReactiveFormsModule,DatePipe,DecimalPipe],template:`
  @if(loading()){<div class="empty-state"><h2>Loading profile…</h2></div>}
  @else if(error()){<div class="empty-state"><h2>Profile unavailable</h2><p>{{error()}}</p></div>}
  @else if(profile();as person){
    @if(editMode){
      <section class="page-heading"><div><p class="eyebrow">YOUR ACCOUNT</p><h1>Edit profile</h1><p>Keep your player information accurate so teammates know what to expect.</p></div></section>
      <form class="form-card feedback-form" [formGroup]="form" (ngSubmit)="save()">
        <label class="upload-box"><input type="file" accept="image/jpeg,image/png,image/webp" (change)="avatarSelected($event)"/><strong>{{selectedAvatar()?'New avatar selected':'Choose profile photo'}}</strong><span>JPEG, PNG or WebP · max 5 MB</span></label>
        <div class="form-grid two"><label>First name<input formControlName="firstName" maxlength="80" /></label><label>Last name<input formControlName="lastName" maxlength="80" /></label></div>
        <label>Location<input formControlName="location" maxlength="160" placeholder="e.g. Kuala Lumpur" /></label>
        <label>Biography<textarea formControlName="biography" rows="5" maxlength="1000" placeholder="Tell other players about yourself."></textarea></label>
        <label>Preferred sports<input formControlName="preferredSports" maxlength="300" placeholder="Badminton, Futsal, Running" /><small>Separate each sport with a comma.</small></label>
        <div class="form-grid two"><label>Skill level<select formControlName="skillLevel"><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option><option value="all_levels">All levels</option></select></label><label>Availability<input formControlName="availability" maxlength="160" placeholder="e.g. Weeknights and weekends" /></label></div>
        @if(saveError()){<div class="alert error" role="alert">{{saveError()}}</div>}
        <div class="form-actions"><a class="button secondary" routerLink="/profile">Cancel</a><button class="button primary" type="submit" [disabled]="saving()">{{saving()?'Saving…':'Save changes'}}</button></div>
      </form>
    }@else{
      <section class="profile-header"><div class="avatar profile-avatar">@if(avatarUrl()){<img [src]="avatarUrl()!" [alt]="person.first_name+' profile photo'"/>}@else{{{initials()}}}</div><div><span class="status-badge" [class.open]="person.status==='active'">{{person.status==='active'?'Active':'Deactivated'}}</span><h1>{{person.first_name}} {{person.last_name}}</h1><p>{{person.location||'Location not added'}} · Last active {{person.last_active_at|date:'d MMM, h:mm a'}}</p><div class="profile-tags">@for(sport of person.preferred_sports;track sport){<span>{{sport}}</span>}@empty{<span>No sports added</span>}</div></div><div class="profile-actions">@if(isOwnProfile){<a class="button secondary" routerLink="/profile/edit">Edit profile</a><a class="button secondary" routerLink="/settings/security">Security</a>}@else if(friendState()==='friend'){<span class="status-badge open">Friends</span>}@else if(friendState()==='received'){<a class="button primary" routerLink="/friend-requests">Respond to request</a>}@else{<button class="button primary" type="button" [disabled]="friendState()==='sent'||sendingFriend()" (click)="addFriend(person.id)">{{sendingFriend()?'Sending…':friendState()==='sent'?'Request sent':'Add friend'}}</button>}</div></section>
      @if(friendMessage()){<div class="alert success" role="status">{{friendMessage()}}</div>}@if(friendError()){<div class="alert error" role="alert">{{friendError()}}</div>}
      <div class="profile-layout"><div><section class="form-card prose-card"><h2>About</h2><p>{{person.biography||'This player has not added a biography yet.'}}</p><div class="profile-details"><div><span>Skill level</span><strong>{{label(person.skill_level)}}</strong></div><div><span>Availability</span><strong>{{person.availability||'Not specified'}}</strong></div><div><span>Ratings received</span><strong>{{person.rating_count}}</strong></div><div><span>Member since</span><strong>{{person.created_at|date:'MMMM y'}}</strong></div></div></section><section class="form-card"><h2>Recent reviews</h2>@for(review of reviews();track review.id){<div class="review"><div><span class="avatar small">{{review.initials}}</span><span><strong>{{review.name}}</strong><small>{{stars(review.rating)}} · {{review.createdAt|date:'d MMM y'}}</small></span></div><p>{{review.comment}}</p></div>}@empty{<p>No written reviews yet.</p>}</section></div><aside><div class="rating-card"><span class="rating-number">{{person.average_rating|number:'1.1-1'}}</span><div><strong>{{person.rating_count?'Player rating':'Not rated yet'}}</strong><p>{{stars(roundedRating())}}</p><small>Based on {{person.rating_count}} {{person.rating_count===1?'rating':'ratings'}}</small></div></div><div class="form-card"><h3>Rating breakdown</h3>@for(row of ratingBreakdown();track row.stars){<div class="rating-row"><span>{{row.stars}} ★</span><span class="bar"><i [style.width.%]="row.percent"></i></span><small>{{row.percent}}%</small></div>}</div></aside></div>
    }
  }
`})
export class ProfilePage implements OnInit{
  private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly auth=inject(AuthService);private readonly supabase=inject(SupabaseService);private readonly friends=inject(FriendRepository);private readonly images=inject(ImageService);private readonly fb=inject(FormBuilder);
  readonly isOwnProfile=!this.route.snapshot.paramMap.get('id');readonly editMode=this.route.snapshot.data['edit']===true;readonly profile=signal<Profile|null>(null);readonly reviews=signal<Review[]>([]);readonly rawRatings=signal<number[]>([]);readonly selectedAvatar=signal<File|null>(null);readonly friendState=signal<string|null>(null);readonly sendingFriend=signal(false);readonly friendMessage=signal('');readonly friendError=signal('');readonly loading=signal(true);readonly error=signal('');readonly saving=signal(false);readonly saveError=signal('');
  readonly form=this.fb.nonNullable.group({firstName:['',[Validators.required,Validators.minLength(1),Validators.maxLength(80)]],lastName:['',[Validators.required,Validators.minLength(1),Validators.maxLength(80)]],location:['',[Validators.maxLength(160)]],biography:['',[Validators.maxLength(1000)]],preferredSports:['',[Validators.maxLength(300)]],skillLevel:['all_levels',[Validators.required]],availability:['',[Validators.maxLength(160)]]});
  readonly initials=computed(()=>{const person=this.profile();return person?`${person.first_name[0]??''}${person.last_name[0]??''}`.toUpperCase():'?';});
  readonly avatarUrl=computed(()=>this.images.publicUrl('avatars',this.profile()?.profile_image_path));
  readonly roundedRating=computed(()=>Math.round(Number(this.profile()?.average_rating??0)));
  readonly ratingBreakdown=computed(()=>{const values=this.rawRatings();return [5,4,3,2,1].map(stars=>({stars,percent:values.length?Math.round(values.filter(value=>value===stars).length/values.length*100):0}));});
  async ngOnInit(){const id=this.route.snapshot.paramMap.get('id')??this.auth.user()?.id;if(!id){this.error.set('No signed-in user was found.');this.loading.set(false);return;}const {data,error}=await this.supabase.client.from('profiles').select('*').eq('id',id).single();if(error||!data){this.error.set(error?.message??'Profile not found.');this.loading.set(false);return;}this.profile.set(data);this.form.setValue({firstName:data.first_name,lastName:data.last_name,location:data.location??'',biography:data.biography??'',preferredSports:data.preferred_sports.join(', '),skillLevel:data.skill_level,availability:data.availability??''});if(!this.editMode){await this.loadReviews(id);if(!this.isOwnProfile)this.friendState.set(await this.friends.relationship(id));}this.loading.set(false);}
  avatarSelected(event:Event){this.selectedAvatar.set((event.target as HTMLInputElement).files?.[0]??null);}
  async save(){this.saveError.set('');if(this.form.invalid){this.form.markAllAsTouched();this.saveError.set('Please correct the highlighted fields.');return;}const id=this.auth.user()?.id;if(!id)return;this.saving.set(true);const current=this.profile();let newAvatar:string|null=null;try{const file=this.selectedAvatar();if(file)newAvatar=await this.images.upload('avatars',id,file);const value=this.form.getRawValue();const preferredSports=[...new Set(value.preferredSports.split(',').map(item=>item.trim()).filter(Boolean))];const changes:Database['public']['Tables']['profiles']['Update']={first_name:value.firstName.trim(),last_name:value.lastName.trim(),location:value.location.trim()||null,biography:value.biography.trim()||null,preferred_sports:preferredSports,skill_level:value.skillLevel,availability:value.availability.trim()||null};if(newAvatar)changes.profile_image_path=newAvatar;const{data,error}=await this.supabase.client.from('profiles').update(changes).eq('id',id).select('*').single();if(error||!data)throw error??new Error('The profile could not be saved.');if(newAvatar&&current?.profile_image_path)await this.images.remove('avatars',current.profile_image_path);this.profile.set(data);window.dispatchEvent(new CustomEvent('jomteam-profile-updated',{detail:{name:`${data.first_name} ${data.last_name}`.trim(),skill:data.skill_level,avatarPath:data.profile_image_path}}));await this.router.navigate(['/profile']);}catch(error){if(newAvatar)await this.images.remove('avatars',newAvatar).catch(()=>undefined);this.saveError.set((error as {message?:string})?.message??'The profile could not be saved.');}finally{this.saving.set(false);}}
  async addFriend(playerId:string){this.sendingFriend.set(true);this.friendMessage.set('');this.friendError.set('');try{await this.friends.send(playerId);this.friendState.set('sent');this.friendMessage.set('Friend request sent.');}catch(error){this.friendError.set((error as {message?:string})?.message??'The friend request could not be sent.');}finally{this.sendingFriend.set(false);}}
  private async loadReviews(id:string){const {data}=await this.supabase.client.from('player_ratings').select('id,rater_id,rating,comment,created_at').eq('rated_user_id',id).order('created_at',{ascending:false});const ratings=data??[];this.rawRatings.set(ratings.map(item=>item.rating));const ids=[...new Set(ratings.map(item=>item.rater_id))];let names=new Map<string,{name:string;initials:string}>();if(ids.length){const {data:people}=await this.supabase.client.from('profiles').select('id,first_name,last_name').in('id',ids);names=new Map((people??[]).map(person=>[person.id,{name:`${person.first_name} ${person.last_name}`.trim(),initials:`${person.first_name[0]??''}${person.last_name[0]??''}`.toUpperCase()}]));}this.reviews.set(ratings.filter(item=>!!item.comment).map(item=>({id:item.id,rating:item.rating,comment:item.comment!,createdAt:item.created_at,name:names.get(item.rater_id)?.name??'JomTeam player',initials:names.get(item.rater_id)?.initials??'JT'})));}
  label(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase());}
  stars(value:number){return '★★★★★'.slice(0,value)+'☆☆☆☆☆'.slice(value);}
}
