import { Injectable, inject } from '@angular/core';
import { SupabaseService } from './supabase.service';

@Injectable({providedIn:'root'})
export class FriendRepository{
  private readonly supabase=inject(SupabaseService);
  async players(){const user=this.supabase.user();if(!user)return[];const {data,error}=await this.supabase.client.from('profiles').select('id,first_name,last_name,location,skill_level,last_active_at').neq('id',user.id).eq('status','active').order('first_name').limit(30);if(error)throw error;const[{data:requests},{data:friendships}]=await Promise.all([this.supabase.client.from('friend_requests').select('sender_id,recipient_id,status').eq('status','pending'),this.supabase.client.from('friendships').select('user_id,friend_id').or(`user_id.eq.${user.id},friend_id.eq.${user.id}`)]);const friendIds=new Set((friendships??[]).map(item=>item.user_id===user.id?item.friend_id:item.user_id));return(data??[]).map(profile=>{const request=requests?.find(item=>(item.sender_id===user.id&&item.recipient_id===profile.id)||(item.recipient_id===user.id&&item.sender_id===profile.id));return{...profile,requestState:friendIds.has(profile.id)?'friend':request?request.sender_id===user.id?'sent':'received':null};});}
  async incoming(){const user=this.supabase.user();if(!user)return[];const {data:requests,error}=await this.supabase.client.from('friend_requests').select('id,sender_id,created_at').eq('recipient_id',user.id).eq('status','pending').order('created_at',{ascending:false});if(error)throw error;if(!requests?.length)return[];const {data:profiles,error:profileError}=await this.supabase.client.from('profiles').select('id,first_name,last_name,location,skill_level').in('id',requests.map(item=>item.sender_id));if(profileError)throw profileError;return requests.map(request=>{const profile=profiles?.find(item=>item.id===request.sender_id);return{id:request.id,playerId:request.sender_id,name:profile?`${profile.first_name} ${profile.last_name}`:'Player',location:profile?.location??'Malaysia',skill:profile?.skill_level??'all_levels'};});}
  async listFriends(){const user=this.supabase.user();if(!user)return[];const {data,error}=await this.supabase.client.from('friendships').select('user_id,friend_id,created_at').or(`user_id.eq.${user.id},friend_id.eq.${user.id}`).order('created_at',{ascending:false});if(error)throw error;const ids=(data??[]).map(item=>item.user_id===user.id?item.friend_id:item.user_id);if(!ids.length)return[];const {data:profiles,error:profileError}=await this.supabase.client.from('profiles').select('id,first_name,last_name,location,skill_level,last_active_at').in('id',ids);if(profileError)throw profileError;return profiles??[];}
  async relationship(playerId:string){const user=this.supabase.user();if(!user)return null;const {data:friendships,error:friendError}=await this.supabase.client.from('friendships').select('user_id,friend_id').or(`user_id.eq.${user.id},friend_id.eq.${user.id}`);if(friendError)throw friendError;if((friendships??[]).some(item=>item.user_id===playerId||item.friend_id===playerId))return'friend';const {data:requests,error}=await this.supabase.client.from('friend_requests').select('sender_id,recipient_id,status').eq('status','pending');if(error)throw error;const request=(requests??[]).find(item=>(item.sender_id===user.id&&item.recipient_id===playerId)||(item.sender_id===playerId&&item.recipient_id===user.id));return request?request.sender_id===user.id?'sent':'received':null;}
  async send(recipientId:string){const {error}=await this.supabase.client.rpc('send_friend_request',{p_recipient_id:recipientId});if(error)throw error;}
  async accept(requestId:string){const {error}=await this.supabase.client.rpc('accept_friend_request',{p_request_id:requestId});if(error)throw error;}
  async reject(requestId:string){const user=this.supabase.user();if(!user)throw new Error('Sign in to manage friend requests.');const{error}=await this.supabase.client.from('friend_requests').update({status:'rejected'}).eq('id',requestId).eq('recipient_id',user.id).eq('status','pending');if(error)throw error;}
  async remove(friendId:string){const user=this.supabase.user();if(!user)throw new Error('Sign in to manage friends.');const first=user.id<friendId?user.id:friendId;const second=user.id<friendId?friendId:user.id;const{error}=await this.supabase.client.from('friendships').delete().eq('user_id',first).eq('friend_id',second);if(error)throw error;}
}
