import { Injectable, inject } from '@angular/core';
import { MatchFilters, MatchSummary } from './models';
import { Database } from './database.types';
import { SupabaseService } from './supabase.service';
import { ImageService } from './image.service';
@Injectable({ providedIn: 'root' })
export class MatchRepository {
  private readonly supabase = inject(SupabaseService); private readonly images=inject(ImageService);
  async search(filters: MatchFilters): Promise<{ items: MatchSummary[]; total: number }> {
    const from = (filters.page - 1) * filters.pageSize; const to = from + filters.pageSize - 1;
    let query = this.supabase.client.from('match_discovery').select('*', { count: 'exact' }).range(from, to);
    if (filters.query) query = query.textSearch('search_document', filters.query, { type: 'websearch' }); if (filters.sport) query = query.eq('sport', filters.sport);
    if (filters.location) query = query.ilike('location', `%${filters.location}%`); if (filters.skillLevel) query = query.eq('skill_level', filters.skillLevel);
    if (filters.status) query = query.eq('status', filters.status); if (filters.date) query = query.gte('starts_at', `${filters.date}T00:00:00`).lt('starts_at', `${filters.date}T23:59:59`);
    query = query.order(filters.sort === 'newest' ? 'created_at' : 'starts_at', { ascending: filters.sort !== 'newest' });
    const { data, count, error } = await query; if (error) throw error;
    return { items: (data ?? []).map((row: Record<string, any>) => ({ id: row['id'], title: row['title'], sport: row['sport'], location: row['location'], startsAt: row['starts_at'], skillLevel: row['skill_level'], participantCount: row['participant_count'], maxPlayers: row['max_players'], status: row['status'], hostName: row['host_name'], hostAvatarUrl: row['host_avatar_url'], coverUrl: row['cover_url'] })), total: count ?? 0 };
  }
  async upcomingForUser():Promise<MatchSummary|null>{const user=this.supabase.user();if(!user)return null;const {data:memberships,error}=await this.supabase.client.from('match_participants').select('match_id').eq('user_id',user.id).is('removed_at',null);if(error)throw error;const joinedIds=(memberships??[]).map(item=>item.match_id);const hostedQuery=this.supabase.client.from('match_discovery').select('*').eq('host_id',user.id).in('status',['open','full']).gte('starts_at',new Date().toISOString()).order('starts_at').limit(1);const joinedQuery=joinedIds.length?this.supabase.client.from('match_discovery').select('*').in('id',joinedIds).in('status',['open','full']).gte('starts_at',new Date().toISOString()).order('starts_at').limit(1):Promise.resolve({data:[],error:null});const [hosted,joined]=await Promise.all([hostedQuery,joinedQuery]);const queryError=hosted.error??joined.error;if(queryError)throw queryError;const row=[...(hosted.data??[]),...(joined.data??[])].sort((a:any,b:any)=>new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime())[0] as Record<string,any>|undefined;return row?{id:row['id'],title:row['title'],sport:row['sport'],location:row['location'],startsAt:row['starts_at'],skillLevel:row['skill_level'],participantCount:row['participant_count'],maxPlayers:row['max_players'],status:row['status'],hostName:row['host_name'],hostAvatarUrl:row['host_avatar_url'],coverUrl:row['cover_url']}:null;}
  async requestToJoin(matchId: string, message?: string) { const { error } = await this.supabase.client.rpc('request_to_join_match',{p_match_id:matchId,p_message:message??null}); if (error) throw error; }
  async cancelJoinRequest(matchId:string){const user=this.supabase.user();if(!user)throw new Error('Sign in to manage your request.');const{error}=await this.supabase.client.from('match_join_requests').update({status:'cancelled'}).eq('match_id',matchId).eq('user_id',user.id).eq('status','pending');if(error)throw error;}
  async leaveMatch(matchId: string) { const { error } = await this.supabase.client.rpc('leave_match',{p_match_id:matchId}); if (error) throw error; }
  async removeParticipant(matchId:string,userId:string){const {error}=await this.supabase.client.rpc('remove_match_participant',{p_match_id:matchId,p_user_id:userId});if(error)throw error;}
  async getParticipants(matchId:string,hostId:string,hostName:string){const players=[{id:hostId,name:hostName,initials:hostName.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase(),isHost:true}];const {data,error}=await this.supabase.client.from('match_participants').select('user_id').eq('match_id',matchId).is('removed_at',null);if(error)throw error;const ids=(data??[]).map(item=>item.user_id).filter(id=>id!==hostId);if(!ids.length)return players;const {data:profiles,error:profileError}=await this.supabase.client.from('profiles').select('id,first_name,last_name').in('id',ids);if(profileError)throw profileError;return players.concat((profiles??[]).map(profile=>{const name=`${profile.first_name} ${profile.last_name}`.trim();return{id:profile.id,name,initials:`${profile.first_name[0]??''}${profile.last_name[0]??''}`.toUpperCase(),isHost:false};}));}
  async getJoinState(matchId:string){const user=this.supabase.user();if(!user)return null;const {data,error}=await this.supabase.client.from('match_join_requests').select('status').eq('match_id',matchId).eq('user_id',user.id).maybeSingle();if(error)throw error;if(data?.status==='accepted')return'accepted';const {data:participant,error:participantError}=await this.supabase.client.from('match_participants').select('match_id').eq('match_id',matchId).eq('user_id',user.id).is('removed_at',null).maybeSingle();if(participantError)throw participantError;return participant?'accepted':data?.status??null;}
  async getMyRatings(matchId:string){const user=this.supabase.user();if(!user)return[];const {data,error}=await this.supabase.client.from('player_ratings').select('rated_user_id,rating,comment').eq('match_id',matchId).eq('rater_id',user.id);if(error)throw error;return data??[];}
  async saveRating(matchId:string,ratedUserId:string,rating:number,comment:string){const user=this.supabase.user();if(!user)throw new Error('Sign in to rate a player.');const {error}=await this.supabase.client.from('player_ratings').upsert({match_id:matchId,rater_id:user.id,rated_user_id:ratedUserId,rating,comment:comment.trim()||undefined},{onConflict:'match_id,rater_id,rated_user_id'});if(error)throw error;}
  async getById(matchId:string){const {data,error}=await this.supabase.client.from('match_discovery').select('*').eq('id',matchId).single();if(error)throw error;return data as Record<string,any>;}
  async getEditableById(matchId:string){const user=this.supabase.user();if(!user)throw new Error('Sign in to edit a match.');const {data,error}=await this.supabase.client.from('matches').select('*').eq('id',matchId).eq('host_id',user.id).single();if(error)throw new Error(error.code==='PGRST116'?'Only the host can edit this match.':error.message);return data;}
  async acceptRequest(requestId: string) { const { data, error } = await this.supabase.client.rpc('accept_match_join_request', { p_request_id: requestId }); if (error) throw error; return data; }
  async rejectRequest(requestId: string) { const { data, error } = await this.supabase.client.rpc('reject_match_join_request', { p_request_id: requestId }); if (error) throw error; return data; }
  async cancelMatch(matchId: string) { const { data, error } = await this.supabase.client.rpc('cancel_match', { p_match_id: matchId }); if (error) throw error; return data; }
  async completeMatch(matchId:string){const{error}=await this.supabase.client.rpc('complete_match',{p_match_id:matchId});if(error)throw error;}
  async pendingHostedRequests(){const user=this.supabase.user();if(!user)return[];const {data:requests,error}=await this.supabase.client.from('match_join_requests').select('id,match_id,user_id,created_at').eq('status','pending').order('created_at',{ascending:false});if(error)throw error;if(!requests?.length)return[];const matchIds=[...new Set(requests.map(item=>item.match_id))];const {data:matches,error:matchError}=await this.supabase.client.from('matches').select('id,title,host_id').in('id',matchIds).eq('host_id',user.id);if(matchError)throw matchError;const hostedRequests=requests.filter(request=>matches?.some(match=>match.id===request.match_id));if(!hostedRequests.length)return[];const userIds=[...new Set(hostedRequests.map(item=>item.user_id))];const {data:profiles,error:profileError}=await this.supabase.client.from('profiles').select('id,first_name,last_name').in('id',userIds);if(profileError)throw profileError;return hostedRequests.map(request=>{const match=matches?.find(item=>item.id===request.match_id);const profile=profiles?.find(item=>item.id===request.user_id);return{id:request.id,matchTitle:match?.title??'Match',playerName:profile?`${profile.first_name} ${profile.last_name}`:'Player',initials:profile?`${profile.first_name[0]??''}${profile.last_name[0]??''}`:'P'};});}
  async create(input:{title:string;sport:string;skillLevel:string;maxPlayers:number;location:string;startsAt:string;durationMinutes:number;description:string;cover:File|null},onProgress?:(value:number)=>void){const user=this.supabase.user();if(!user)throw new Error('Sign in to create a match.');const {data,error}=await this.supabase.client.from('matches').insert({host_id:user.id,title:input.title,sport:input.sport,skill_level:input.skillLevel,max_players:input.maxPlayers,location:input.location,starts_at:new Date(input.startsAt).toISOString(),duration_minutes:input.durationMinutes,description:input.description,status:'draft'}).select('id').single();if(error)throw error;try{let cover_image_path:string|undefined;if(input.cover)cover_image_path=await this.images.upload('match-covers',data.id,input.cover,onProgress);const {error:updateError}=await this.supabase.client.from('matches').update({cover_image_path,status:'open'}).eq('id',data.id);if(updateError)throw updateError;return data.id;}catch(cause){await this.supabase.client.from('matches').delete().eq('id',data.id);throw cause;}}
  async update(matchId:string,input:{title:string;sport:string;skillLevel:string;maxPlayers:number;location:string;startsAt:string;durationMinutes:number;description:string;cover:File|null},onProgress?:(value:number)=>void){const current=await this.getEditableById(matchId);if(current.status==='completed'||current.status==='cancelled')throw new Error('Completed or cancelled matches cannot be edited.');if(input.maxPlayers<current.participant_count)throw new Error(`Capacity cannot be lower than the current ${current.participant_count} players.`);let newCover:string|null=null;try{if(input.cover)newCover=await this.images.upload('match-covers',matchId,input.cover,onProgress);const changes:Database['public']['Tables']['matches']['Update']={title:input.title,sport:input.sport,skill_level:input.skillLevel,max_players:input.maxPlayers,location:input.location,starts_at:new Date(input.startsAt).toISOString(),duration_minutes:input.durationMinutes,description:input.description||null,status:current.participant_count>=input.maxPlayers?'full':'open'};if(newCover)changes.cover_image_path=newCover;const {error}=await this.supabase.client.from('matches').update(changes).eq('id',matchId).eq('host_id',current.host_id!);if(error)throw error;if(newCover&&current.cover_image_path)await this.supabase.client.storage.from('match-covers').remove([current.cover_image_path]);}catch(error){if(newCover)await this.supabase.client.storage.from('match-covers').remove([newCover]);throw error;}}
}
